name: Generate Snake Animation
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (3:00 AM EAT)
  workflow_dispatch: # Allows manual triggering
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create dist directory
        run: mkdir -p dist # Ensures dist/ exists
      - uses: platane/snk@v3
        with:
          github_user_name: Canol001
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          git commit -m "Update snake animation"
          git push
